<?php

/**
 * @file
 *  Common Object Oriented Library module
 *
 * This module enhances the Drupal DX through classes and helpers
 */

/**
 * Implements hook_menu().
 */
function cool_menu() {
  $items = array();
  $classes = \Drupal\cool\Loader::mapImplementationsAvailable('PageControllers', '\Drupal\cool\Controllers\PageController');
  foreach ($classes as $class_name) {
    if (method_exists($class_name, 'getDefinition')) {
      if (!method_exists($class_name, 'pageCallback')) {
        throw new Exception(t('Class @classname do not have the pageCallback method', array('@classname' => $class_name)));
      }
      $items[$class_name::getPath()] = array_merge(
          array(
        'page callback' => 'cool_default_page_callback',
        'page arguments' => array($class_name),
        'access callback' => 'cool_default_page_access_callback',
        'access arguments' => array($class_name),
          ), $class_name::getDefinition()
      );
    }
  }
  return $items;
}

/**
 * Default function to call the page callback from page controller classes
 * @param string $class_name
 */
function cool_default_page_callback($class_name) {
  return $class_name::pageCallback();
}

/**
 * Default function to call the page access callback from page controller classes
 * @param string $class_name
 */
function cool_default_page_access_callback($class_name) {
  return $class_name::accessCallback();
}
